kind: Deployment
apiVersion: apps/v1
metadata:
  name: table-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-metrics-app
  template:
    metadata:
      labels:
        app: table-metrics-app
    spec:
      containers:
        - name: table-metrics
          image: python-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: table-metrics
spec:
ports:
  - name: http-8081
    port: 8080
    protocol: TCP
    targetPort: 8080
selector:
  app: table-metrics-app
